-- VoyageAI Database Schema
-- Run via: bun run db:setup
-- Requires DATABASE_URL environment variable to be set

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── trips ────────────────────────────────────────────────────────────────────
-- Stores trip plans created by users through the AI planning wizard.
CREATE TABLE IF NOT EXISTS trips (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  destination     TEXT NOT NULL,
  start_date      DATE NOT NULL,
  end_date        DATE NOT NULL,
  budget          TEXT NOT NULL DEFAULT 'mid-range'
                    CHECK (budget IN ('economy', 'mid-range', 'luxury')),
  vibe            TEXT NOT NULL DEFAULT 'mixed'
                    CHECK (vibe IN ('relaxed', 'adventurous', 'cultural', 'foodie', 'mixed')),
  pace            TEXT NOT NULL DEFAULT 'balanced'
                    CHECK (pace IN ('packed', 'balanced', 'slow')),
  travelers       TEXT NOT NULL DEFAULT 'solo'
                    CHECK (travelers IN ('solo', 'couple', 'family', 'group')),
  interests       TEXT[] NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Speed up lookups by destination and creation date.
CREATE INDEX IF NOT EXISTS idx_trips_destination ON trips (destination);
CREATE INDEX IF NOT EXISTS idx_trips_created_at ON trips (created_at DESC);

-- ── itineraries ──────────────────────────────────────────────────────────────
-- Stores the day-by-day itinerary generated by the AI for a given trip.
CREATE TABLE IF NOT EXISTS itineraries (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id         UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  day_number      INTEGER NOT NULL CHECK (day_number >= 1),
  date            DATE NOT NULL,
  activities      JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Each trip can only have one entry per day.
  UNIQUE (trip_id, day_number)
);

-- Fetch all days for a trip quickly.
CREATE INDEX IF NOT EXISTS idx_itineraries_trip_id ON itineraries (trip_id, day_number);

-- ── bookings ─────────────────────────────────────────────────────────────────
-- Placeholder booking records — affiliate links the user can click through to
-- complete a purchase on a partner site.
CREATE TABLE IF NOT EXISTS bookings (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id         UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  type            TEXT NOT NULL CHECK (type IN ('flight', 'hotel', 'activity', 'dining', 'car_rental')),
  provider        TEXT NOT NULL,
  title           TEXT NOT NULL,
  description     TEXT,
  amount          NUMERIC(10, 2),
  currency        TEXT NOT NULL DEFAULT 'USD',
  url             TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Fetch all bookings for a given trip.
CREATE INDEX IF NOT EXISTS idx_bookings_trip_id ON bookings (trip_id, type);